### ISSUE TITLE
Unity3D support?

### ISSUE THREAD

**Issue by katopz** [bubbafat/FirebaseSharp#13]
I use `nuget` to add this lib to Unity5 project via VS2015 v14 but it throw...

```
Severity    Code    Description Project File    Line
Error       Could not install package 'Microsoft.Bcl.Build 1.0.14'. You are trying to install this package into a project that targets '.NETFramework,Version=v3.5,Profile=Unity Subset v3.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

So it's not support Unity am I right? Or maybe some magic workaround to make it work?

Thanks

**Comment by katopz** [comment]
nvm

**Comment by DennisSmolek** [comment]
@katopz What did you do to get this to work? I'm attempting the same thing and dont know if I should write my own or use a library like this one..

**Comment by katopz** [comment]
@DennisSmolek Na, I end up write my own REST at that time. But I think you should be more lucky today. please do try here https://github.com/firebase/Firebase-Unity

PS : I didn't try it yet ;)

**Comment by DennisSmolek** [comment]
Hey @katopz thanks for the update! I too have written my own REST wrapper but I'm concerned with having multiple SSE streams open Vs the websocket...

I tried porting the Firebase Jar with IKVM and haven't figured that out.. 

Thank you for the link, I actually started with that but they dont support the WebGL or Windows Store which are the two big platforms I need at the moment... I guess for now I'll stick with my wrapper until something changes..
