### ISSUE TITLE
OutOfMemoryException

### ISSUE THREAD

**Issue by MykolaDiachok** [bubbafat/FirebaseSharp#17]
When I add a large number of objects - the system uses more than 2GB.

System.OutOfMemoryException was unhandled
Message: An unhandled exception of type 'System.OutOfMemoryException' occurred in mscorlib.dll

How to reset the cache?
How do I know that the object is loaded?

**Comment by bubbafat** [comment]
There is no way to reset the cache.  The cache represents a single copy of the entire JSON object you have subscribed to - to clear it would mean you would no longer have that object.  If that is the behavior you want then subscribe to more granular paths.
