### ISSUE TITLE
handle keep-alive timeout

### ISSUE THREAD

**Issue by eyasso** [bubbafat/FirebaseSharp#6]
Hi bubbafat,

Second issue i saw is that you don't handle keep-alive timeout.

So i did some research and think this is what should be done:
1. in file Response.cs, you should declare a timer with timeout twice the interval between keep-alive. 
keep-alive timeout is 30 seconds. So the interval should be 60 seconds.
2. In ReadLoop() method start the timer, just before while(true).
in following code block:
if(read.StartsWith( "event: " ))
{
//handle keep-alive.
}

//Copy to above block
if(eventName == "keep-alive")
{
    lock(_keepAliveLock)
    {
        _keepAliveTimer.Stop();
    }
}

if the keepAliveTimer function is called, this means that keep-alive timeout occurred.
If that happens, you should dispose the object and send notification to user.

**Comment by bubbafat** [comment]
Thanks for looking at this - I'll put together a fix sometime in the next
week or so as time permits.

If you need to have a fix sooner, please consider submitting a pull request
with your change.

Thanks,

Robert.

**Comment by bubbafat** [comment]
Hmmm ... my previous comment was meant for your other note on #1 

There is no reason to handle the keep-alive event.  It sends a little data over the wire to keep the response open but it doesn't include a payload and it does not require a response.

Is there a scenario where you believe having the keep-alive event would be useful?

**Comment by eyasso** [comment]
Hi,

I tested to see what happens if I unplug the Ethernet cable.
This caused keep-alive to stop receiving.
I believe, in that case, the connection is closed from other side, but we don't get indication.
So when keep-alive timer invokes, you should dispose the response (closed the connection in our side also).
Beside, monitoring keep-alive is something must be. If keep alive is stopped being received, than it means the connection is not alive.

Following is your code with some changes I believe needed to be done in order to support
keep-alive timeout. It needs some polish...

public void Cancel()
{
    //stop keep-alive timer
    _keepAliveTimer.Stop();
    _cancel.Cancel();
}

//keep-alive timer
void KeepAliveTimerCallback( object sender, System.Timers.ElapsedEventArgs e )
{
    lock(_keepAliveLock)
    {
        _continueWaitForEvent = false;
        _keepAliveTimer.Stop();
        _response.Dispose();
    }
}

//reads events from server
private async Task ReadLoop(  )
{
    try
    {
        using(_response)
        using(var content = await _response.Content.ReadAsStreamAsync())
        using(StreamReader sr = new StreamReader( content ))
        {
            string eventName = null;
            //start the keep alive timer
            _keepAliveTimer.Start();
            while(_continueWaitForEvent)
            {
                string read = await sr.ReadLineAsync().ConfigureAwait( false );
                ...
                ...
                ...
                if(read.StartsWith( "event: " ))
                {
                    eventName = read.Substring( 7 );
                    if(eventName == "auth_revoked")
                    {
                        //upload the event to the user. user should handle that event and dispose the
                        FirebaseSharp object
                        OnAuthRevoked();
                    } 
                    else if(eventName == "keep-alive")
                    {
                        lock(_keepAliveLock)
                        {
                            //restart keep alive timer
                            _keepAliveTimer.Stop();
                            _keepAliveTimer.Start();
                        }
                    }
                            continue;
                }
            ....
            ....
            }
}

**Comment by bubbafat** [comment]
I am considering an approach that does not require a timer - rather it uses a cancellation token to add a configurable timeout to the reads.

You can see an example of what I mean here:

https://github.com/bubbafat/FirebaseSharp/commit/377210bb5b8fe90548291ad469552c114d49f732#diff-c26ebb41a81c2de798eb4d92a487990aR1

And here:

https://github.com/bubbafat/FirebaseSharp/commit/377210bb5b8fe90548291ad469552c114d49f732#diff-a60f96c7c6285c6d07e14dc4c6ba2f2bR1

I'll think a bit more and do some testing but that's where I'm heading now.

**Comment by bubbafat** [comment]
Please consider trying the 2.0 alpha - since I'm not fixing 1.0 bugs any longer I am closing this issue.  More details about 2.0 alpha are here:

http://www.roberthorvick.com/2015/07/27/firebasesharp-2-goes-alpha/
