### ISSUE TITLE
Put and PutAsync Method Issue

### ISSUE THREAD

**Issue by vineetsalvi** [bubbafat/FirebaseSharp#8]
When I use Put Method then the data gets updated into Firebase. But It halts after sometime automatically telling to use PutAsync method.
When I use PutAsync method the value gets updated with random numbers i.e. sometimes show higher values and sometimes show lower values for a particular key.

**Comment by bubbafat** [comment]
The 2.0 alpha library was release this morning on nuget.org - it is marked as a prerelease package so you won't see it by default.  It more closely conforms to the Firebase Node API and fixed a ton of bugs.  I won't be doing any more maintenance on the 1.0 version.

Details about it and some examples are here:

http://www.roberthorvick.com/2015/07/27/firebasesharp-2-goes-alpha/
